// comandos/vdr.js

export default async (sock, m, args, extra) => {
    // Desestructuramos solo lo que se necesita de extra (en este caso, solo jid)
    const { jid } = extra;

    const verdades = [
        '¿Cuál es tu mayor miedo?',
        '¿A quién amas en secreto?',
        '¿Cuál es tu secreto más vergonzoso?',
        '¿Alguna vez mentiste a un amigo cercano?',
        '¿A quién del grupo besarías?',
        '¿Qué es lo más ilegal que has hecho?',
        '¿Tienes alguna fantasía secreta?',
        '¿Alguna vez stalkeaste a alguien? ¿A quién?',
        '¿A qué ex extrañas?',
        '¿Cuál fue la última mentira que dijiste?',
        '¿Qué harías si fueras invisible por un día?',
        '¿Con quién del grupo tendrías una cita?',
        '¿Has enviado un mensaje hot por error?',
        '¿Has tenido un amor prohibido?',
        '¿Cuál ha sido tu peor cita?',
        '¿Te arrepientes de algo con una ex pareja?',
        '¿Cuál ha sido tu peor error en la vida?',
        '¿Qué parte de tu cuerpo no te gusta y por qué?',
        '¿Alguna vez copiaste en un examen?',
        '¿A quién del grupo le contarías un gran secreto?',
        '¿Alguna vez hablaste mal de alguien del grupo?',
        '¿Qué es lo más raro que te han dicho en redes sociales?',
        '¿A qué persona famosa te gustaría besar?',
        '¿Cuál fue tu último pensamiento antes de dormir ayer?',
        '¿Has tenido un sueño subido de tono con alguien del grupo?',
        '¿Te has enamorado de alguien por internet sin conocerlo en persona?',
        '¿Cuál ha sido tu mayor ridículo en público?',
        '¿Alguna vez fingiste estar enfermo para evitar algo?',
        '¿Te han roto el corazón? ¿Quién fue?',
        '¿Qué es lo más infantil que sigues haciendo?',
        '¿Tienes un crush en este grupo? ¿Quién?',
        '¿Alguna vez robaste algo? ¿Qué fue?',
        '¿Cuál ha sido tu mayor logro personal?',
        '¿Alguna vez fingiste querer a alguien que no te gustaba?',
        '¿Has revisado el celular de tu pareja sin permiso?',
        '¿Alguna vez escribiste una carta de amor? ¿A quién?',
        '¿Quién es la última persona a la que stalkeaste en redes?',
        '¿Has mentido para quedar bien con alguien?',
        '¿Alguna vez fuiste infiel?',
        '¿Tienes algún fetiche raro?',
        '¿Qué es lo que más te molesta de alguien en este grupo?',
        '¿Cuál ha sido tu fantasía más loca?',
        '¿Quién fue tu primer amor y qué pasó?',
        '¿Has fingido reírte de un chiste malo de alguien del grupo?',
        '¿Alguna vez fuiste rechazado/a públicamente?',
        '¿Cuál ha sido el peor apodo que te han puesto?',
        '¿Con qué personaje ficticio tendrías una cita?',
        '¿Si tuvieras que eliminar a alguien del grupo, quién sería y por qué?',
        // Tus nuevas preguntas
        '¿Cuál es el peor regalo que has recibido?',
        '¿Qué harías si solo te quedara un día de vida?',
        '¿Cuál es tu mayor inseguridad?',
        '¿Qué es lo más loco que has hecho por amor?',
        '¿Has tenido alguna experiencia paranormal?',
        '¿Qué hábito te gustaría cambiar?',
        '¿Cuál es tu guilty pleasure?',
        '¿Cuál fue tu peor metida de pata?',
        '¿Qué es lo que más te gusta de ti?',
        '¿Has tenido un crush con alguien prohibido?',
        // Más preguntas para mayor variedad
        '¿Cuál es la cosa más extraña que has comido?',
        '¿Si pudieras tener un superpoder, cuál sería y por qué?',
        '¿Qué te hace sentir más orgulloso de ti mismo?',
        '¿Qué es lo más aventurero que has hecho?',
        '¿Cuál es tu mayor arrepentimiento en la vida?',
        '¿Qué te irrita más de la gente en general?',
        '¿Has roto alguna ley alguna vez (aunque sea menor)?',
        '¿Qué canción cantas a todo pulmón cuando estás solo?',
        '¿Cuál es la opinión más impopular que tienes?',
        '¿Qué harías si ganaras la lotería hoy?'
    ];

    const retos = [
        'Cambia de personaje a uno de Peppa Pig por 5 minutos.',
        'Envía un mensaje random a alguien y muéstralo.',
        'Escribe una confesión falsa y menciona a alguien del grupo.',
        'Canta una canción de Maluma.',
        'Hazle una declaración de amor a alguien del grupo.',
        'Escribe tu nombre al revés y mándalo con emoción.',
        'Envía un sticker vergonzoso que tengas.',
        'Actúa como robot durante 2 minutos.',
        'Di un trabalenguas difícil.',
        'Imita la voz de un famoso.',
        'Di un piropo a la persona que mencionaste por última vez.',
        'Haz un dibujo en Paint, súbelo y mándalo.',
        'Di 3 verdades incómodas sobre ti.',
        'Escribe el abecedario sin usar vocales.',
        'Escribe un mensaje usando solo emojis.',
        'Haz una videollamada al azar del grupo.',
        'Habla como un bebé por 3 minutos.',
        'Ponte un filtro ridículo y mándalo al grupo.',
        'Escribe una mini historia cursi protagonizada por alguien del grupo.',
        'Escribele a un integrante de tu mismo país, haciéndole creer que lo conoces irl (que no esté participando en el juego).',
        'Escribe tu mayor secreto... pero cámbiale todos los nombres.',
        'Manda un mensaje diciendo algo vergonzoso como si fuera una confesión.',
        'Haz como si dieras las noticias pero con puro chisme del grupo.',
        'Haz una imitación de tu profesor más raro.',
        'Dibuja un autorretrato con los ojos cerrados y muéstralo.',
        'Cambia tu foto de perfil por algo gracioso por 10 minutos.',
        'Haz un audio actuando como si estuvieras llorando por amor.',
        'Lee un mensaje viejo vergonzoso del grupo (si tienes alguno guardado).',
        'Haz una lista de 5 crushes ficticios y di por qué te gustan.',
        'Graba un audio diciendo una frase muy cursi como si fueras actor de telenovela.',
        'Haz un poema improvisado para alguien del grupo.',
        'Actúa como si fueras influencer famoso durante 2 minutos.',
        'Publica una historia en WhatsApp con una frase random que te dé el grupo.',
        'Haz una escena dramática como si fueras de una novela mexicana.',
        'Pide perdón públicamente por algo que no hiciste.',
        'Declara tu amor por el objeto más cercano que tengas a la mano.',
        'Haz un video vendiendo un producto imaginario como si fueras influencer.',
        'Escribe una canción improvisada con los nombres de 3 personas del grupo.',
        'Haz un tutorial falso sobre cómo ligar por WhatsApp.',
        'Haz un rol actuando como si fueras un extraterrestre llegando a la Tierra.',
        'Canta el abecedario como si fuera una canción romántica.',
        // Tus nuevos retos
        'Envía un meme que te represente.',
        'Haz 10 sentadillas y mándalo en video.',
        'Cuenta un chiste que siempre te haga reír.',
        'Haz una pausa dramática y di "Esto es serio..."',
        'Haz una rima improvisada sobre el grupo.',
        'Imita a un animal y que los demás adivinen cuál es.',
        'Escribe una frase motivacional para todos.',
        'Haz un reto de tongue twister y mándalo en audio.',
        'Haz un mini baile ridículo y envíalo.',
        'Haz una confesión graciosa que nunca hayas contado.',
        // Más retos para mayor variedad
        'Graba un audio cantando el estribillo de tu canción favorita desafinando a propósito.',
        'Envía una foto de tus calcetines (los que lleves puestos ahora mismo).',
        'Haz una reseña de un objeto random de tu habitación como si fuera un producto de lujo.',
        'Escribe un microcuento de terror en 3 líneas.',
        'Inventa un saludo secreto para el grupo y enséñalo.',
        'Haz un audio susurrando un secreto gracioso.',
        'Envía el último emoji que usaste 10 veces seguidas.',
        'Haz un truco de magia (aunque sea uno muy simple) y envíalo en video.',
        'Escribe un tweet que te haga parecer un robot.',
        'Envía una foto de tu desayuno/cena/comida más reciente (no tiene que ser elegante).'
    ];

    // Elegir modo aleatorio
    const modo = Math.random() < 0.5 ? 'Verdad' : 'Reto';
    const lista = modo === 'Verdad' ? verdades : retos;
    const item = lista[Math.floor(Math.random() * lista.length)];

    // Enviar el mensaje
    await sock.sendMessage(
        jid, // Usa jid de extra para enviar al chat correcto
        { text: `🎲 *${modo}*: ${item}` },
        { quoted: m }
    );
};